# coding: utf-8

# flake8: noqa

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.activities_api import ActivitiesApi
from swagger_client.api.athletes_api import AthletesApi
from swagger_client.api.clubs_api import ClubsApi
from swagger_client.api.gears_api import GearsApi
from swagger_client.api.routes_api import RoutesApi
from swagger_client.api.segment_efforts_api import SegmentEffortsApi
from swagger_client.api.segments_api import SegmentsApi
from swagger_client.api.streams_api import StreamsApi
from swagger_client.api.uploads_api import UploadsApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.activity_stats import ActivityStats
from swagger_client.models.activity_total import ActivityTotal
from swagger_client.models.activity_type import ActivityType
from swagger_client.models.activity_zone import ActivityZone
from swagger_client.models.altitude_stream import AltitudeStream
from swagger_client.models.base_stream import BaseStream
from swagger_client.models.cadence_stream import CadenceStream
from swagger_client.models.club_activity import ClubActivity
from swagger_client.models.club_athlete import ClubAthlete
from swagger_client.models.comment import Comment
from swagger_client.models.detailed_activity import DetailedActivity
from swagger_client.models.detailed_athlete import DetailedAthlete
from swagger_client.models.detailed_club import DetailedClub
from swagger_client.models.detailed_gear import DetailedGear
from swagger_client.models.detailed_segment import DetailedSegment
from swagger_client.models.detailed_segment_effort import DetailedSegmentEffort
from swagger_client.models.distance_stream import DistanceStream
from swagger_client.models.error import Error
from swagger_client.models.explorer_response import ExplorerResponse
from swagger_client.models.explorer_segment import ExplorerSegment
from swagger_client.models.fault import Fault
from swagger_client.models.heart_rate_zone_ranges import HeartRateZoneRanges
from swagger_client.models.heartrate_stream import HeartrateStream
from swagger_client.models.lap import Lap
from swagger_client.models.lat_lng import LatLng
from swagger_client.models.lat_lng_stream import LatLngStream
from swagger_client.models.meta_activity import MetaActivity
from swagger_client.models.meta_athlete import MetaAthlete
from swagger_client.models.meta_club import MetaClub
from swagger_client.models.moving_stream import MovingStream
from swagger_client.models.photos_summary import PhotosSummary
from swagger_client.models.photos_summary_primary import PhotosSummaryPrimary
from swagger_client.models.polyline_map import PolylineMap
from swagger_client.models.power_stream import PowerStream
from swagger_client.models.power_zone_ranges import PowerZoneRanges
from swagger_client.models.route import Route
from swagger_client.models.smooth_grade_stream import SmoothGradeStream
from swagger_client.models.smooth_velocity_stream import SmoothVelocityStream
from swagger_client.models.split import Split
from swagger_client.models.sport_type import SportType
from swagger_client.models.stream_set import StreamSet
from swagger_client.models.summary_activity import SummaryActivity
from swagger_client.models.summary_athlete import SummaryAthlete
from swagger_client.models.summary_club import SummaryClub
from swagger_client.models.summary_gear import SummaryGear
from swagger_client.models.summary_pr_segment_effort import SummaryPRSegmentEffort
from swagger_client.models.summary_segment import SummarySegment
from swagger_client.models.summary_segment_effort import SummarySegmentEffort
from swagger_client.models.temperature_stream import TemperatureStream
from swagger_client.models.time_stream import TimeStream
from swagger_client.models.timed_zone_distribution import TimedZoneDistribution
from swagger_client.models.timed_zone_range import TimedZoneRange
from swagger_client.models.updatable_activity import UpdatableActivity
from swagger_client.models.upload import Upload
from swagger_client.models.waypoint import Waypoint
from swagger_client.models.zone_range import ZoneRange
from swagger_client.models.zone_ranges import ZoneRanges
from swagger_client.models.zones import Zones
